packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  sharp: true
  "@tailwindcss/oxide": true
  esbuild: true
  workerd: true
onlyBuiltDependencies:
  - sharp
  - "@tailwindcss/oxide"
  - esbuild
  - workerd
