import Link from "next/link";
import type { Conflict, ProposedAssignment, UnfilledSlot } from "@sundayplan/sdk";
import { Badge, Card, CardHeader, ScoreBar } from "@/components/ui";

const RULE_LABEL: Record<string, string> = {
  double_booking: "Double booking",
  unavailable: "Unavailable",
  same_day: "Two services, one day",
  over_max_per_month: "Over monthly cap",
  skill_gap: "Skill gap",
  unfilled_near_deadline: "Unfilled slot",
  consecutive_sundays: "Consecutive Sundays",
  family_conflict: "Family clash",
  key_person_unavailable: "Lead unavailable",
  credential_gap: "Credential gap",
};

type TFn = (key: string, vars?: Record<string, string | number>) => string;

// The fix each rule points the planner toward — every CTA jumps to the exact
// cell in the schedule grid, where the assign picker / remove tools live.
const RULE_ACTION: Record<string, string> = {
  double_booking: "Reassign",
  unavailable: "Reassign",
  same_day: "Review",
  over_max_per_month: "Rebalance",
  skill_gap: "Pick trained",
  unfilled_near_deadline: "Fill slot",
  consecutive_sundays: "Rebalance",
  family_conflict: "Review",
  key_person_unavailable: "Review",
  credential_gap: "Reassign",
};

// i18n key per action, used when a `t` is supplied (English map above is the fallback).
const RULE_ACTION_KEY: Record<string, string> = {
  double_booking: "conflict.action.reassign",
  unavailable: "conflict.action.reassign",
  same_day: "conflict.action.review",
  over_max_per_month: "conflict.action.rebalance",
  skill_gap: "conflict.action.pickTrained",
  unfilled_near_deadline: "conflict.action.fillSlot",
  consecutive_sundays: "conflict.action.rebalance",
  family_conflict: "conflict.action.review",
  key_person_unavailable: "conflict.action.review",
  credential_gap: "conflict.action.reassign",
};

/** Deep-link to the offending cell: `?focus` drives the highlight, `#` scrolls. */
function resolveHref(c: Conflict): string | null {
  if (!c.service_id) return null;
  const key = c.role_id ? `${c.service_id}:${c.role_id}` : c.service_id;
  const hash = c.role_id ? `#cell-${c.service_id}-${c.role_id}` : "";
  return `/schedule?focus=${encodeURIComponent(key)}${hash}`;
}

const UNFILLED_REASON: Record<string, string> = {
  no_eligible_candidates: "No eligible candidates",
  insufficient_candidates: "Not enough candidates",
};

export function AutoFillProposal({
  assignments,
  unfilled,
  roleNames,
  memberNames,
}: {
  assignments: ProposedAssignment[];
  unfilled: UnfilledSlot[];
  roleNames: Record<string, string>;
  memberNames: Record<string, string>;
}) {
  return (
    <Card>
      <CardHeader
        title="Auto-fill proposal"
        sub="Generated by the deterministic scoring engine — review and send"
        action={<Badge tone="gold">{assignments.length} proposed</Badge>}
      />
      <ul className="divide-y divide-white/[0.05]">
        {assignments.map((a) => (
          <li key={`${a.service_id}-${a.role_id}-${a.member_id}`} className="px-5 py-4">
            <div className="flex items-baseline justify-between gap-4">
              <div className="flex items-baseline gap-2.5">
                <span className="text-sm font-medium text-ink-50">{memberNames[a.member_id] ?? a.member_id}</span>
                <span className="text-xs text-ink-500">{roleNames[a.role_id] ?? a.role_id}</span>
                {a.rank > 1 ? <span className="text-[0.7rem] text-ink-600">candidate #{a.rank}</span> : null}
              </div>
              <span className="tabular-nums text-sm font-semibold text-gold-300">{a.score.total}</span>
            </div>
            <div className="mt-3">
              <ScoreBar score={a.score} />
            </div>
            {a.score.warnings.length > 0 ? (
              <div className="mt-2 text-xs text-[color:var(--color-warning)]">⚠ {a.score.warnings.join(" · ")}</div>
            ) : null}
          </li>
        ))}
        {unfilled.map((u) => (
          <li key={`${u.service_id}-${u.role_id}-unfilled`} className="flex items-center justify-between px-5 py-4">
            <div className="flex items-center gap-2.5">
              <span className="text-sm font-medium text-ink-300">{roleNames[u.role_id] ?? u.role_id}</span>
              <span className="text-xs text-ink-500">{u.filled}/{u.needed} filled</span>
            </div>
            <Badge tone="warning">{UNFILLED_REASON[u.reason] ?? u.reason}</Badge>
          </li>
        ))}
      </ul>
    </Card>
  );
}

export function ConflictPanel({
  conflicts,
  roleNames,
  memberNames,
  t,
}: {
  conflicts: Conflict[];
  roleNames: Record<string, string>;
  memberNames: Record<string, string>;
  /** When provided, labels are localised; otherwise English (admin fallback). */
  t?: TFn;
}) {
  const hard = conflicts.filter((c) => c.severity === "hard").length;
  const actionLabel = (rule: string) =>
    t ? t(RULE_ACTION_KEY[rule] ?? "conflict.action.resolve") : RULE_ACTION[rule] ?? "Resolve";
  return (
    <Card>
      <CardHeader
        title={t ? t("conflict.title") : "Conflict checks"}
        sub={t ? t("conflict.found", { count: conflicts.length }) : `${conflicts.length} found across the schedule`}
        action={
          hard > 0 ? (
            <Badge tone="danger">{t ? t("conflict.hard", { count: hard }) : `${hard} hard`}</Badge>
          ) : (
            <Badge tone="success">{t ? t("conflict.noHard") : "no hard conflicts"}</Badge>
          )
        }
      />
      <ul className="divide-y divide-white/[0.05]">
        {conflicts.map((c, i) => {
          const who = c.member_id ? memberNames[c.member_id] ?? c.member_id : null;
          const role = c.role_id ? roleNames[c.role_id] ?? c.role_id : null;
          const href = resolveHref(c);
          return (
            <li key={i} className="flex items-start gap-3 px-5 py-3.5">
              <span className="mt-0.5">
                <Badge tone={c.severity === "hard" ? "danger" : "warning"}>{RULE_LABEL[c.rule] ?? c.rule}</Badge>
              </span>
              <div className="min-w-0 flex-1">
                <p className="text-sm text-ink-200">{c.message}</p>
                {(who || role) && (
                  <p className="mt-0.5 text-xs text-ink-500">
                    {[who, role].filter(Boolean).join(" · ")}
                  </p>
                )}
              </div>
              {href ? (
                <Link
                  href={href}
                  className="shrink-0 rounded-md bg-white/[0.06] px-2.5 py-1 text-xs text-ink-200 transition-colors hover:bg-gold-400/90 hover:text-ink-950"
                >
                  {actionLabel(c.rule)} →
                </Link>
              ) : null}
            </li>
          );
        })}
        {conflicts.length === 0 ? (
          <li className="px-5 py-6 text-center text-sm text-ink-500">
            {t ? t("conflict.clear") : "No conflicts — you're clear to send."}
          </li>
        ) : null}
      </ul>
    </Card>
  );
}
