import type { Conflict, ProposedAssignment, UnfilledSlot } from "@sundayplan/sdk";
import { Badge, Card, CardHeader, ScoreBar } from "@/components/ui";

const RULE_LABEL: Record<string, string> = {
  double_booking: "Double booking",
  unavailable: "Unavailable",
  same_day: "Two services, one day",
  over_max_per_month: "Over monthly cap",
  skill_gap: "Skill gap",
  unfilled_near_deadline: "Unfilled slot",
  consecutive_sundays: "Consecutive Sundays",
};

const UNFILLED_REASON: Record<string, string> = {
  no_eligible_candidates: "No eligible candidates",
  insufficient_candidates: "Not enough candidates",
};

export function AutoFillProposal({
  assignments,
  unfilled,
  roleNames,
  memberNames,
}: {
  assignments: ProposedAssignment[];
  unfilled: UnfilledSlot[];
  roleNames: Record<string, string>;
  memberNames: Record<string, string>;
}) {
  return (
    <Card>
      <CardHeader
        title="Auto-fill proposal"
        sub="Generated by the deterministic scoring engine — review and send"
        action={<Badge tone="gold">{assignments.length} proposed</Badge>}
      />
      <ul className="divide-y divide-white/[0.05]">
        {assignments.map((a) => (
          <li key={`${a.service_id}-${a.role_id}-${a.member_id}`} className="px-5 py-4">
            <div className="flex items-baseline justify-between gap-4">
              <div className="flex items-baseline gap-2.5">
                <span className="text-sm font-medium text-ink-50">{memberNames[a.member_id] ?? a.member_id}</span>
                <span className="text-xs text-ink-500">{roleNames[a.role_id] ?? a.role_id}</span>
                {a.rank > 1 ? <span className="text-[0.7rem] text-ink-600">candidate #{a.rank}</span> : null}
              </div>
              <span className="tabular-nums text-sm font-semibold text-gold-300">{a.score.total}</span>
            </div>
            <div className="mt-3">
              <ScoreBar score={a.score} />
            </div>
            {a.score.warnings.length > 0 ? (
              <div className="mt-2 text-xs text-[color:var(--color-warning)]">⚠ {a.score.warnings.join(" · ")}</div>
            ) : null}
          </li>
        ))}
        {unfilled.map((u) => (
          <li key={`${u.service_id}-${u.role_id}-unfilled`} className="flex items-center justify-between px-5 py-4">
            <div className="flex items-center gap-2.5">
              <span className="text-sm font-medium text-ink-300">{roleNames[u.role_id] ?? u.role_id}</span>
              <span className="text-xs text-ink-500">{u.filled}/{u.needed} filled</span>
            </div>
            <Badge tone="warning">{UNFILLED_REASON[u.reason] ?? u.reason}</Badge>
          </li>
        ))}
      </ul>
    </Card>
  );
}

export function ConflictPanel({
  conflicts,
  roleNames,
  memberNames,
}: {
  conflicts: Conflict[];
  roleNames: Record<string, string>;
  memberNames: Record<string, string>;
}) {
  const hard = conflicts.filter((c) => c.severity === "hard").length;
  return (
    <Card>
      <CardHeader
        title="Conflict checks"
        sub={`${conflicts.length} found across the schedule`}
        action={hard > 0 ? <Badge tone="danger">{hard} hard</Badge> : <Badge tone="success">no hard conflicts</Badge>}
      />
      <ul className="divide-y divide-white/[0.05]">
        {conflicts.map((c, i) => {
          const who = c.member_id ? memberNames[c.member_id] ?? c.member_id : null;
          const role = c.role_id ? roleNames[c.role_id] ?? c.role_id : null;
          return (
            <li key={i} className="flex items-start gap-3 px-5 py-3.5">
              <span className="mt-0.5">
                <Badge tone={c.severity === "hard" ? "danger" : "warning"}>{RULE_LABEL[c.rule] ?? c.rule}</Badge>
              </span>
              <div className="min-w-0">
                <p className="text-sm text-ink-200">{c.message}</p>
                {(who || role) && (
                  <p className="mt-0.5 text-xs text-ink-500">
                    {[who, role].filter(Boolean).join(" · ")}
                  </p>
                )}
              </div>
            </li>
          );
        })}
      </ul>
    </Card>
  );
}
